openapi: 3.0.0
info:
  title: Booking System API
  version: 1.0.0
  description: API documentation for the Booking System.

paths:
  /booking:
    post:
      summary: Create a new booking
      operationId: createBooking
      requestBody:
        description: Booking creation request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '200':
          description: Booking successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'

components:
  schemas:
    CreateBookingRequest:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
          description: ID of the customer
        showId:
          type: integer
          format: int64
          description: ID of the show
        showSeatsId:
          type: array
          items:
            type: integer
            format: int64
          description: List of selected show seat IDs
      required:
        - customerId
        - showId
        - showSeatsId

    Booking:
      type: object
      properties:
        customer:
          $ref: '#/components/schemas/Customer'
        show:
          $ref: '#/components/schemas/Show'
        seats:
          type: array
          items:
            $ref: '#/components/schemas/ShowSeat'
        amount:
          type: number
          format: double
        bookedAt:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - CONFIRMED
            - CANCELLED
            - PENDING
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payment'

    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        city:
          type: string
        phoneNumber:
          type: string
        email:
          type: string

    Show:
      type: object
      properties:
        id:
          type: integer
          format: int64
        startTime:
          type: string
          format: date-time
        duration:
          type: integer
          format: int32
        startDate:
          type: string
          format: date
        hall:
          $ref: '#/components/schemas/Hall'
        isDeleted:
          type: boolean
        isOnline:
          type: boolean

    ShowSeat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        seat:
          $ref: '#/components/schemas/Seat'
        status:
          type: string
          enum:
            - AVAILABLE
            - BOOKED
            - RESERVED

    Payment:
      type: object
      properties:
        reference:
          type: string
        amount:
          type: number
          format: double
        providerType:
          type: string
          enum:
            - CARD
            - CASH
            - WALLET
        status:
          type: string
          enum:
            - SUCCESS
            - FAILED
            - PENDING

    Hall:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        features:
          type: array
          items:
            type: string
            enum:
              - DOLBY
              - IMAX
              - THREE_D

    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        rowNo:
          type: integer
        columnNo:
          type: integer
        seatType:
          type: string
          enum:
            - REGULAR
            - PREMIUM
            - VIP
